### ISSUE TITLE
Fix option to markdown check does nothing and may be hiding actual errors?

### ISSUE THREAD

**Issue by rngadam** [ai-cfia/github-workflows#89]
This needs some investigation because we are using the "fix" option to auto-fix issues found by the linter:

https://github.com/ai-cfia/github-workflows/blob/6e2c2f0c2ba9236ef498d425ce47d71388fd879f/.github/workflows/workflow-markdown-check.yml#L29

However, looking at the source code https://github.com/DavidAnson/markdownlint-cli2-action I cannot see anything else than calling the underlying linter with --fix; this would fix errors it can autofix, but to be useful these changes would then also need to be autocommitted back to the repo (which to me, seems like a bad idea to add commits). 

Plus, the warnings that get fixed probably are not reported? Defeating the purpose of the linter.

Needs testing as I suspect some linter warnings (such as linting out inline HTML) are not getting reported.

**Comment by ThomasCardin** [comment]
Thanks for the issue, but you forgot to tag the issue as `todo` in the project section.

**Comment by rngadam** [comment]
> Thanks for the issue, but you forgot to set the status of the issue as `todo` in the project section.

Should it really? My perspective is that items added from non-DevSecOps should get added to the backlog and then reviewed by the DevSecOps team to see if it's an issue that they think should be done. And then schedule to iteration.

**Comment by ThomasCardin** [comment]
I agree. Good point here, this allows us to filter the requests

**Comment by SonOfLope** [comment]
Repositories that now need to be updated after this fix since they use custom config files:

- [ ] https://github.com/ai-cfia/finesse-frontend/blob/main/.github/workflows/react-frontend-workflow.yml
- [ ] https://github.com/ai-cfia/dev-rel-docs/pull/123
- [ ] https://github.com/ai-cfia/llamaindex-db/blob/main/.github/workflows/github-workflows.yaml
- [ ] https://github.com/ai-cfia/nachet-frontend/blob/main/.github/workflows/react-frontend-workflows.yml
